### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by ced59ric** [chrisnappin/play-recaptcha#1]
Hi,

Thanks a lot for your amazing work. I would like to know if is it possible to add a Java API ?

Thank you.

**Comment by chrisnappin** [comment]
Hi Cedric,

  Many thanks for the interest. I'm not familiar with using Play with Java, but if I get the chance I'll look into it. I'd also be happy to accept a pull request ;-)

Cheers,

  Chris

**Comment by chrisnappin** [comment]
Hi Cedric,

  I've looked into this, but there seem to be limitations in mixing the two different Scala and Java Play APIs for forms and i18n in the one application (or module). Specifically, enabling the Java APIs results in the Scala APIs not working properly. I've posted a question about this a few days ago on the Play Google Group and on Stackoverflow, with no response so far.

The short of it is that this means I'd need to write a completely new, separate module to add Java APIs. I'm unlikely to have the time to do that I'm afraid.

If I get time I'll raise a Play framework bug report but it might be closed as working as desired.

Sorry,

  Chris

**Comment by ced59ric** [comment]
Hi,

Sorry for the late response, I was in vacation and completely forgot about my request..

I searched for a workaround too but ended up in the same way as you when mixing up the Java and Scala Play API's.

As an example, SecureSocial built their module in Scala and then added a Java API. 
https://github.com/jaliss/securesocial/tree/master/module-code/app/securesocial/core/java

I would love to contribute but unfortunately my Scala knowledge is non-existent..

Anyway, thanks a lot for your time :-)
