### ISSUE TITLE
Integration with Silhouette + option for removing labels

### ISSUE THREAD

**Issue by serversideapps** [chrisnappin/play-recaptcha#11]
Hi!

I managed to integrate your module with the Silhouette seed example. While this is not a bug, neither your fault, reCaptcha does not work out of the box with Silhoutte. I had a hard time figuring out why, but finally I got it: Silhoutte Content Security Policies disable loading the Google script, you have to add authorizations for this manually. My integrated project's [Wiki page](https://github.com/serversideapps/silhmo/wiki) has the workaround. I just let you know this in case you want to give a hint in your documentation in this direction.

A little thing which has to do with your project: while the labels for the recaptcha field can be configured, the place holders for them cannot be removed. So even if I use empty labels, they eat up some space. I put the whole recaptcha field in a div and gave it a negative margin but this is not very elegant.

Anyway, your project is amazing, keep it up!

**Comment by chrisnappin** [comment]
Hi,

  Thanks for the hint, I've not used Silhouette myself.

I hope to add some extra customisation of the generated HTML in the next release, in the meantime as a work-around you can copy [recaptchaField.scala.html](https://github.com/chrisnappin/play-recaptcha/blob/release-2.1/app/views/recaptcha/recaptchaField.scala.html) into your codebase and change the HTML wrapping around the reCAPTCHA div to be anything you need, for example if you are using Bootstrap or don't want labels.

Hope that helps!

**Comment by chrisnappin** [comment]
Options to customise HTML have been added
