### ISSUE TITLE
Add version for play 2.6 

### ISSUE THREAD

**Issue by sergeda** [chrisnappin/play-recaptcha#13]
Play Framework 2.6 soon will be out. Please, make version of your module for play 2.6

**Comment by chrisnappin** [comment]
Great, many thanks. I'll add this to the project backlog.

**Comment by jducoeur** [comment]
Any idea what the timing for version 2.3 of the library is likely to be?  I need to add RECAPTCHA for a Play 2.6 site I'm building, and I'm wondering whether I should wait for the release, or fork the current state.

**Comment by akitaylor** [comment]
I've just asked this question, the new version is expected later this week.

**Comment by jducoeur** [comment]
Excellent -- thanks!

**Comment by chrisnappin** [comment]
Release published, enjoy!
