### ISSUE TITLE
Work in scala version 2.9.1 and play version 2.0.6

### ISSUE THREAD

**Issue by lucasscarduelli** [chrisnappin/play-recaptcha#15]
It's possible this plugin work in a project with scala version 2.9.1 and play version 2.0.6?

**Comment by lucasscarduelli** [comment]
Any news!!??

**Comment by chrisnappin** [comment]
Hi sorry, missed this. Are you sure about play 2.0.6? You really shouldn't be using that in production?

**Comment by chrisnappin** [comment]
Not sure if Play v2 that old even has a documented plugin mechanism, but if it does it'll be completely different to the current one, so this would require pretty much re-writing the whole project. Not sure the demand is there to warrant this. Closing as won't fix.
