### ISSUE TITLE
Persian Language

### ISSUE THREAD

**Issue by SoheilJafari** [chrisnappin/play-recaptcha#16]
Add persian ("fa") to support language.
Google supports persian language.

**Comment by chrisnappin** [comment]
Hi, really sorry for the very slow response! play-recaptcha already supports all languages that Google recaptcha supports, including Persian. Take a https://github.com/chrisnappin/play-recaptcha/blob/release-2.3/docs/high-level-api.md#internationalisation to choose which way to configure your app. Please re-open if you have any more issues.
