### ISSUE TITLE
Migrating => Play 2.6 error: object recaptchaWidget is not a member of package views.html.recaptcha

### ISSUE THREAD

**Issue by bravegag** [chrisnappin/play-recaptcha#17]
While migrating a project to Play 2.6 and the latest 2.3 version I get the following error:
> error: object recaptchaWidget is not a member of package views.html.recaptcha
>

This among other errors I didn't have before:
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:20: value isInternalErrorCode is not a member of object com.nappin.play.recaptcha.RecaptchaErrorCode
>[error] @recaptchaError = @{ errorCode.filter(code => !RecaptchaErrorCode.isInternalErrorCode(code)) }
>[error]                                                                   ^
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:25: object recaptchaWidget is not a member of package views.html.recaptcha
>[error] Note: class recaptchaWidget exists, but it has no companion object.
>[error]         <div class="col-md-7">@recaptcha.recaptchaWidget(tabindex = tabindex, includeNoScript = includeNoScript)</div>
>[error]                                          ^
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:25: reassignment to val
>[error]         <div class="col-md-7">@recaptcha.recaptchaWidget(tabindex = tabindex, includeNoScript = includeNoScript)</div>
>[error]                                                                   ^
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:25: reassignment to val
>[error]         <div class="col-md-7">@recaptcha.recaptchaWidget(tabindex = tabindex, includeNoScript = includeNoScript)</div>
>[error]                                                                                               ^

The code I'm working on can be found here:
https://github.com/bravegag/play-authenticate-usage-scala/tree/migrate-play-2.6

More specifically here:
https://github.com/bravegag/play-authenticate-usage-scala/blob/migrate-play-2.6/app/views/_recaptchaFieldPartial.scala.html

**Comment by chrisnappin** [comment]
Many thanks, I'll take a look

**Comment by chrisnappin** [comment]
Hi, I've had a look at your project and it seems you've cloned then customised the widget renderer (recaptchaField.scala.html) in your previous code, to alter the HTML. I suggest you clone the latest version of this view template (https://github.com/chrisnappin/play-recaptcha/blob/master/app/views/recaptcha/recaptchaField.scala.html) as you are missing quite a few changes that should hopefully resolve your errors.

Please comment here if this sorts things?

Thanks, Chris

**Comment by bravegag** [comment]
@chrisnappin Hi hi! thanks for the fast response and taking a look! Thank you for pointing me to the updates. I later realized the 2.6 major changes of injecting stuff rather than using global objects so I fixed this.

So far it all compiles and runs fine now however, the recaptcha widget doesn't render in my 2.6 version. I have compared the HTML sources generated before and after migrating to 2.6 for the signup page that uses your widget and they are identical. Therefore, I was wondering whether you made changes to the recaptcha widget configuration file `recaptcha.conf` or whether there would be any other reason for the recaptchaWidget not rendering?

Other than that I don't understand why it doesn't render.

**Comment by bravegag** [comment]
@chrisnappin Hi again! Now it works :) the culprit for the no rendering is one of the following new default 2.6 filters so I disabled them all. I need to find out which one specifically is preventing recaptcha from rendering though ... ez trial and error :D 

The widget now renders and seems to be working allright by modifying `application.conf` adding the following: 

```
    play.filters.disabled += play.filters.csrf.CSRFFilter
    play.filters.disabled += play.filters.headers.SecurityHeadersFilter
    play.filters.disabled += play.filters.hosts.AllowedHostsFilter
```

**Comment by chrisnappin** [comment]
Ah, take a look at https://github.com/chrisnappin/play-recaptcha/blob/release-2.3/docs/high-level-api.md#security

**Comment by chrisnappin** [comment]
You really shouldn't check your Google reCaptcha private key into public GitHub, by the way.

**Comment by bravegag** [comment]
Oopsie It is registered for my localhost so shouldn't matter or? :(

**Comment by chrisnappin** [comment]
Closing as resolved.
