### ISSUE TITLE
Not working with Play 2.4 Guice DI

### ISSUE THREAD

**Issue by ssteward54** [chrisnappin/play-recaptcha#2]
It looks like this needs to be updated to be compatible with the Play 2.4 Guice Dependency Injection. I'm getting this error when trying to use it in Play 2.4.

Could not find a suitable constructor in com.nappin.play.recaptcha.RecaptchaPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
at com.nappin.play.recaptcha.RecaptchaPlugin.class(RecaptchaPlugin.scala:25)
while locating com.nappin.play.recaptcha.RecaptchaPlugin

**Comment by chrisnappin** [comment]
Hi,

Thanks for using play-recaptcha.

I'll look into porting play-recaptcha to v2.4, and maybe converting from a Plugin to a Module. I take it you are looking (or already are) using Play 2.4 in production?

This will be a breaking (incompatible) change, so if anyone wants to use play-recaptcha with Play 2.3 they can use the current release instead (which I can branch and maintain if needed).

Cheers,

Chris

**Comment by ssteward54** [comment]
Yes we are building a production site with it, thanks!

**Comment by chrisnappin** [comment]
Hi, this has now been resolved by release 1.5, which should sync across maven central in the next couple of hours. I'll update the wiki over the next few days, but in the meantime simply copy one of the 2 example projects. This plugin has been converted to a DI module and uses the Play 2.4 APIs, other than that there is no change. Any feedback you can provide would be really useful!

Enjoy, Chris

**Comment by chrisnappin** [comment]
Hi,

 I've created v1.5 to support Play 2.4, and have just updated the wiki with instructions. Please let me know how you get on!

Cheers,

  Chris

On 1 September 2015 18:01:31 BST, ssteward54 notifications@github.com wrote:

> Yes we are building a production site with it, thanks!
> 
> On Tue, Sep 1, 2015, 10:58 AM Chris Nappin notifications@github.com
> wrote:
> 
> > Hi,
> > 
> > Thanks for using play-recaptcha.
> > 
> > I'll look into porting play-recaptcha to v2.4, and maybe converting
> > from a
> > Plugin to a Module. I take it you are looking (or already are) using
> > Play
> > 2.4 in production?
> > 
> > This will be a breaking (incompatible) change, so if anyone wants to
> > use
> > play-recaptcha with Play 2.3 they can use the current release instead
> > (which I can branch and maintain if needed).
> > 
> > Cheers,
> > 
> > Chris
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/chrisnappin/play-recaptcha/issues/2#issuecomment-136769139
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chrisnappin/play-recaptcha/issues/2#issuecomment-136795952

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ssteward54** [comment]
Thanks, I'll try it out today!

**Comment by ssteward54** [comment]
Ok just wanted to let you know we implemented the new version and it's
working great, thanks!
