### ISSUE TITLE
Add support for version 2.12

### ISSUE THREAD

**Issue by KeivanAbdi** [chrisnappin/play-recaptcha#23]
In documentation it is mentioned that Play reCAPTCHA 2.5 is released for Scala 2.12 but it is not available in [maven](https://mvnrepository.com/artifact/com.nappin/play-recaptcha) repository.

**Comment by chrisnappin** [comment]
Many thanks for raising this, looks like I made a manual error with the 2.5 release that I never noticed! I'll look into whether Maven Central will allow me to add a Scala 2.12 version, or whether I'll need to create a new minor release version

**Comment by chrisnappin** [comment]
All resolved, maven central is now updated: https://search.maven.org/artifact/com.nappin/play-recaptcha_2.12/2.5/jar

**Comment by chrisnappin** [comment]
Thanks again @KeivanAbdi for raising the issue, without this I'd have probably never noticed!
