### ISSUE TITLE
How to unit test the recaptcha upon form submission?

### ISSUE THREAD

**Issue by ssteward54** [chrisnappin/play-recaptcha#3]
I'm trying to write some unit tests for the form submission that is using the play-recaptcha plugin and having a little bit of a struggle with it. Do you have any examples on how to write tests against the bindFromRequest / form fold code?

Here's an example of what the code looks like. I tried mocking some of the recaptcha methods but it's getting pretty hair pretty quick and I was hoping you had some examples. Thanks!

  def submit = Action.async { implicit request =>
    implicit val context = scala.concurrent.ExecutionContext.Implicits.global

```
recaptchaVerifier.bindFromRequestAndVerify(creditCardForm).map { form =>
  form.fold(
    errors => {
      BadRequest(views.html.addCreditCards(errors))
    },
    success => {
      response.status match {
        case "SUCCESS" => Redirect(routes.Success.index)
        case _ => Redirect(routes.Error.index)
      }
    })
}
```

  }

**Comment by andrestc** [comment]
I'm having the same struggle. Any help?

**Comment by ssteward54** [comment]
I ended up figuring out the problem > it's a type mismatch dealing with Futures. The recaptchaVerifier is  asynchronous so it returns a Future form whereas the regular Play form is not a Future. So, You just need to use an async action, so in the above code example, the Action def should just be something like:

`def submit = Action.async {`

instead of 

`def submit = Action {`

In Play, if you're returning a Future from the result in your actions, just use Action.async and it handles it for you.

**Comment by chrisnappin** [comment]
Hi,

  I've added an example unit test (using Specs 2 and Mockito) to the "play-recaptcha-v2-example" app, please see:

https://github.com/chrisnappin/play-recaptcha-v2-example/blob/master/test/controllers/ExampleFormSpec.scala

Please let me know if this is useful, and matches how you like to do your unit testing.

Yes, testing with Futures does get quite hairy - if you look through the unit tests for "play-recaptcha" itself you'll see some other examples that might also help.

Many thanks,

  Chris
