### ISSUE TITLE
Support for AJAX submission

### ISSUE THREAD

**Issue by varju** [chrisnappin/play-recaptcha#4]
`RecaptchaVerifier.bindFromRequestAndVerify` takes a `Request[AnyContent]`, but then it calls `request.body.asFormUrlEncoded.get`.  This means it will only actually work with `Request[AnyContentAsFormUrlEncoded]`.  I'm specifically interested in posting a JSON body.

Play's `Form.bindFromRequest` has logic to convert many different body types into `Map[String, Seq[String]]`.  I'm a bit of a novice when it comes to the forms code, and I couldn't think of any easy way to reuse their logic here.

**Comment by chrisnappin** [comment]
Hi,

  Thanks for your interest! Maybe if you could provide an example Ajax form I can have a look into wheather support could be added?

Cheers,

  Chris

**Comment by chrisnappin** [comment]
Support for AJAX, and example added
