### ISSUE TITLE
Low level recaptcha.recaptchaWidget doesn't use language from Messages

### ISSUE THREAD

**Issue by sergeda** [chrisnappin/play-recaptcha#8]
I have a problem with translating recaptcha.recaptchaWidget 
I'm passing Messages with Lang code ru but this still shows text in English. As I understand script tag should be with hl argument like this:

`<script type="text/javascript" src="https://www.google.com/recaptcha/api.js?hl=es">`
But on my page this script doesn't have hl argument

**Comment by chrisnappin** [comment]
Hi sergeda,

  Thanks for using play-recaptcha. I assume you are using Recaptcha v2? The Google Javascript automatically detects the language settings of your user's web browser, and uses that. Please see https://developers.google.com/recaptcha/docs/language.

Are you actually wanting to override the web browser language settings and force the Recaptcha widget to render in Russian? That would seem to be what the "hl" argument can achieve. If so I can add support for that in a new release, triggered from an explicit application setting?

Are you using Play 2.5 and play-recaptcha 2.0?

Many thanks,

  Chris

**Comment by sergeda** [comment]
@chrisnappin Yes, I'm using Recaptcha v2. play-recaptcha 1.5 and Play 2.4 in particular.
It would be great to be able to override the web browser language settings passing explicit parameter into the widget. In my application user can select any language he wants despite what browser language setting is.

Thanks a lot,
Sergey

**Comment by chrisnappin** [comment]
Hi, I've included some functionality in the latest release (v2.1) to do this for you - set "recaptcha.languageMode" to "play" and it will convert your Play locale (Messages) to language (and possibly country) codes to pass to the reCAPTCHA widget.
