### ISSUE TITLE
Better customization of the generated HTML

### ISSUE THREAD

**Issue by bravegag** [chrisnappin/play-recaptcha#9]
First of all, thank you for this great plugin! it is very well done! I integrated the plugin in this project [play-authenticate-usage-scala](https://github.com/bravegag/play-authenticate-usage-scala) which I plan to use as template for a new Web App. 

In that project we use Twitter Bootstrap which requires customizing the HTML generation of the form fields (and of the reCAPTCHA field). The issue is that I could not find any way to customize the generated HTML e.g. when using `recaptchaField.scala.html` the only way I found was to copy paste `recaptchaField.scala.html` in my project and change it to fit the Twitter Bootstrap requirements and it is still not optimal because I can't e.g. add classes `form-control` to the class of the `g-recaptcha` div. 

See [twitterBootstrapRecaptchaField.scala.html](https://github.com/bravegag/play-authenticate-usage-scala/blob/master/app/views/twitterBootstrapRecaptchaField.scala.html) and [signup.scala.html](https://github.com/bravegag/play-authenticate-usage-scala/blob/master/app/views/signup.scala.html)

A nicer solution would be to create something alla Play where the user has full control of the generated HTML ... this is just an illustrative example taken from the Play for Scala book but of course having a robust componentized `recaptcha` field that allows its HTML to be customized would be great:

    @helper.input(myForm("mydatetime")) { (id, name, value, args) =>
        <input type="datetime" name="@name" id="@id" value="@value" @toHtmlArgs(args)>
     }

I am still learning how to create reusable HTML components in Play and find out whether this can be done better than how I solved it ... so potentially expect a PR too :)

**Comment by chrisnappin** [comment]
Hi, many thanks for the feedback and glad to see use of this project!

Yes, that is a good suggestion and I'd be happy to add something into the next release. I'm no expert on bootstrap though, so if you can summarise all of your requirements that will help me not miss something essential. A PR or some testing will also help ;-)

Looking at the latest Play documentation I think I need to investigate custom field constructors.

**Comment by chrisnappin** [comment]
It's not the solution proposed above but it will let you achieve the same thing - I've added support for HTML attributes for the recaptchaField and recaptchaWidget templates, so you can pass extra CSS classes etc in. Combining this with having your own custom version of recaptchaField (using divs instead of dl/dd/dt) should allow you to use bootstrap more easily.
